version: "3.1"

services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - 8080:8080
