'use client';

export default function ColorPlatter({ Color , setColor }) {

	return (
		<>
        <button className="bg-white w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("white")}/>
        <button className="bg-slate-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-100")}/>
        <button className="bg-slate-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-200")}/>
        <button className="bg-slate-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-300")}/>
        <button className="bg-slate-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-400")}/>
        <button className="bg-slate-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-500")}/>
        <button className="bg-slate-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-600")}/>
        <button className="bg-slate-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-700")}/>
        <button className="bg-slate-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-800")}/>
        <button className="bg-slate-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-900")}/>
        <button className="bg-slate-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("slate-950")}/>
        <button className="bg-gray-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-50")}/>
        <button className="bg-gray-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-100")}/>
        <button className="bg-gray-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-200")}/>
        <button className="bg-gray-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-300")}/>
        <button className="bg-gray-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-400")}/>
        <button className="bg-gray-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-500")}/>
        <button className="bg-gray-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-600")}/>
        <button className="bg-gray-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-700")}/>
        <button className="bg-gray-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-800")}/>
        <button className="bg-gray-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-900")}/>
        <button className="bg-gray-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("gray-950")}/>
        <button className="bg-zinc-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-50")}/>
        <button className="bg-zinc-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-100")}/>
        <button className="bg-zinc-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-200")}/>
        <button className="bg-zinc-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-300")}/>
        <button className="bg-zinc-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-400")}/>
        <button className="bg-zinc-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-500")}/>
        <button className="bg-zinc-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-600")}/>
        <button className="bg-zinc-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-700")}/>
        <button className="bg-zinc-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-800")}/>
        <button className="bg-zinc-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-900")}/>
        <button className="bg-zinc-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("zinc-950")}/>
        <button className="bg-neutral-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-50")}/>
        <button className="bg-neutral-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-100")}/>
        <button className="bg-neutral-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-200")}/>
        <button className="bg-neutral-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-300")}/>
        <button className="bg-neutral-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-400")}/>
        <button className="bg-neutral-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-500")}/>
        <button className="bg-neutral-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-600")}/>
        <button className="bg-neutral-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-700")}/>
        <button className="bg-neutral-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-800")}/>
        <button className="bg-neutral-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-900")}/>
        <button className="bg-neutral-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("neutral-950")}/>
        <button className="bg-stone-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-50")}/>
        <button className="bg-stone-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-100")}/>
        <button className="bg-stone-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-200")}/>
        <button className="bg-stone-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-300")}/>
        <button className="bg-stone-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-400")}/>
        <button className="bg-stone-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-500")}/>
        <button className="bg-stone-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-600")}/>
        <button className="bg-stone-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-700")}/>
        <button className="bg-stone-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-800")}/>
        <button className="bg-stone-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-900")}/>
        <button className="bg-stone-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("stone-950")}/>
        <button className="bg-red-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-50")}/>
        <button className="bg-red-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-100")}/>
        <button className="bg-red-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-200")}/>
        <button className="bg-red-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-300")}/>
        <button className="bg-red-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-400")}/>
        <button className="bg-red-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-500")}/>
        <button className="bg-red-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-600")}/>
        <button className="bg-red-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-700")}/>
        <button className="bg-red-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-800")}/>
        <button className="bg-red-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-900")}/>
        <button className="bg-red-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("red-950")}/>
        <button className="bg-orange-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-50")}/>
        <button className="bg-orange-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-100")}/>
        <button className="bg-orange-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-200")}/>
        <button className="bg-orange-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-300")}/>
        <button className="bg-orange-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-400")}/>
        <button className="bg-orange-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-500")}/>
        <button className="bg-orange-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-600")}/>
        <button className="bg-orange-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-700")}/>
        <button className="bg-orange-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-800")}/>
        <button className="bg-orange-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-900")}/>
        <button className="bg-orange-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("orange-950")}/>
        <button className="bg-amber-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-50")}/>
        <button className="bg-amber-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-100")}/>
        <button className="bg-amber-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-200")}/>
        <button className="bg-amber-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-300")}/>
        <button className="bg-amber-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-400")}/>
        <button className="bg-amber-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-500")}/>
        <button className="bg-amber-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-600")}/>
        <button className="bg-amber-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-700")}/>
        <button className="bg-amber-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-800")}/>
        <button className="bg-amber-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-900")}/>
        <button className="bg-amber-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("amber-950")}/>
        <button className="bg-yellow-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-50")}/>
        <button className="bg-yellow-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-100")}/>
        <button className="bg-yellow-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-200")}/>
        <button className="bg-yellow-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-300")}/>
        <button className="bg-yellow-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-400")}/>
        <button className="bg-yellow-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-500")}/>
        <button className="bg-yellow-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-600")}/>
        <button className="bg-yellow-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-700")}/>
        <button className="bg-yellow-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-800")}/>
        <button className="bg-yellow-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-900")}/>
        <button className="bg-yellow-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("yellow-950")}/>
        <button className="bg-lime-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-50")}/>
        <button className="bg-lime-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-100")}/>
        <button className="bg-lime-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-200")}/>
        <button className="bg-lime-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-300")}/>
        <button className="bg-lime-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-400")}/>
        <button className="bg-lime-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-500")}/>
        <button className="bg-lime-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-600")}/>
        <button className="bg-lime-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-700")}/>
        <button className="bg-lime-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-800")}/>
        <button className="bg-lime-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-900")}/>
        <button className="bg-lime-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("lime-950")}/>
        <button className="bg-green-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-50")}/>
        <button className="bg-green-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-100")}/>
        <button className="bg-green-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-200")}/>
        <button className="bg-green-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-300")}/>
        <button className="bg-green-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-400")}/>
        <button className="bg-green-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-500")}/>
        <button className="bg-green-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-600")}/>
        <button className="bg-green-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-700")}/>
        <button className="bg-green-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-800")}/>
        <button className="bg-green-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-900")}/>
        <button className="bg-green-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("green-950")}/>
        <button className="bg-emerald-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-50")}/>
        <button className="bg-emerald-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-100")}/>
        <button className="bg-emerald-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-200")}/>
        <button className="bg-emerald-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-300")}/>
        <button className="bg-emerald-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-400")}/>
        <button className="bg-emerald-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-500")}/>
        <button className="bg-emerald-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-600")}/>
        <button className="bg-emerald-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-700")}/>
        <button className="bg-emerald-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-800")}/>
        <button className="bg-emerald-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-900")}/>
        <button className="bg-emerald-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("emerald-950")}/>
        <button className="bg-teal-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-50")}/>
        <button className="bg-teal-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-100")}/>
        <button className="bg-teal-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-200")}/>
        <button className="bg-teal-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-300")}/>
        <button className="bg-teal-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-400")}/>
        <button className="bg-teal-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-500")}/>
        <button className="bg-teal-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-600")}/>
        <button className="bg-teal-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-700")}/>
        <button className="bg-teal-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-800")}/>
        <button className="bg-teal-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-900")}/>
        <button className="bg-teal-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("teal-950")}/>
        <button className="bg-cyan-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-50")}/>
        <button className="bg-cyan-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-100")}/>
        <button className="bg-cyan-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-200")}/>
        <button className="bg-cyan-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-300")}/>
        <button className="bg-cyan-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-400")}/>
        <button className="bg-cyan-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-500")}/>
        <button className="bg-cyan-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-600")}/>
        <button className="bg-cyan-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-700")}/>
        <button className="bg-cyan-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-800")}/>
        <button className="bg-cyan-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-900")}/>
        <button className="bg-cyan-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("cyan-950")}/>
        <button className="bg-sky-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-50")}/>
        <button className="bg-sky-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-100")}/>
        <button className="bg-sky-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-200")}/>
        <button className="bg-sky-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-300")}/>
        <button className="bg-sky-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-400")}/>
        <button className="bg-sky-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-500")}/>
        <button className="bg-sky-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-600")}/>
        <button className="bg-sky-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-700")}/>
        <button className="bg-sky-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-800")}/>
        <button className="bg-sky-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-900")}/>
        <button className="bg-sky-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("sky-950")}/>
        <button className="bg-blue-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-50")}/>
        <button className="bg-blue-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-100")}/>
        <button className="bg-blue-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-200")}/>
        <button className="bg-blue-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-300")}/>
        <button className="bg-blue-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-400")}/>
        <button className="bg-blue-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-500")}/>
        <button className="bg-blue-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-600")}/>
        <button className="bg-blue-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-700")}/>
        <button className="bg-blue-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-800")}/>
        <button className="bg-blue-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-900")}/>
        <button className="bg-blue-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("blue-950")}/>
        <button className="bg-indigo-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-50")}/>
        <button className="bg-indigo-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-100")}/>
        <button className="bg-indigo-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-200")}/>
        <button className="bg-indigo-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-300")}/>
        <button className="bg-indigo-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-400")}/>
        <button className="bg-indigo-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-500")}/>
        <button className="bg-indigo-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-600")}/>
        <button className="bg-indigo-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-700")}/>
        <button className="bg-indigo-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-800")}/>
        <button className="bg-indigo-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-900")}/>
        <button className="bg-indigo-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("indigo-950")}/>
        <button className="bg-violet-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-50")}/>
        <button className="bg-violet-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-100")}/>
        <button className="bg-violet-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-200")}/>
        <button className="bg-violet-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-300")}/>
        <button className="bg-violet-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-400")}/>
        <button className="bg-violet-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-500")}/>
        <button className="bg-violet-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-600")}/>
        <button className="bg-violet-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-700")}/>
        <button className="bg-violet-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-800")}/>
        <button className="bg-violet-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-900")}/>
        <button className="bg-violet-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("violet-950")}/>
        <button className="bg-purple-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-50")}/>
        <button className="bg-purple-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-100")}/>
        <button className="bg-purple-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-200")}/>
        <button className="bg-purple-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-300")}/>
        <button className="bg-purple-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-400")}/>
        <button className="bg-purple-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-500")}/>
        <button className="bg-purple-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-600")}/>
        <button className="bg-purple-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-700")}/>
        <button className="bg-purple-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-800")}/>
        <button className="bg-purple-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-900")}/>
        <button className="bg-purple-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("purple-950")}/>
        <button className="bg-fuchsia-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-50")}/>
        <button className="bg-fuchsia-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-100")}/>
        <button className="bg-fuchsia-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-200")}/>
        <button className="bg-fuchsia-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-300")}/>
        <button className="bg-fuchsia-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-400")}/>
        <button className="bg-fuchsia-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-500")}/>
        <button className="bg-fuchsia-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-600")}/>
        <button className="bg-fuchsia-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-700")}/>
        <button className="bg-fuchsia-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-800")}/>
        <button className="bg-fuchsia-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-900")}/>
        <button className="bg-fuchsia-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("fuchsia-950")}/>
        <button className="bg-pink-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-50")}/>
        <button className="bg-pink-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-100")}/>
        <button className="bg-pink-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-200")}/>
        <button className="bg-pink-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-300")}/>
        <button className="bg-pink-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-400")}/>
        <button className="bg-pink-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-500")}/>
        <button className="bg-pink-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-600")}/>
        <button className="bg-pink-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-700")}/>
        <button className="bg-pink-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-800")}/>
        <button className="bg-pink-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-900")}/>
        <button className="bg-pink-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("pink-950")}/>
        <button className="bg-rose-50 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-50")}/>
        <button className="bg-rose-100 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-100")}/>
        <button className="bg-rose-200 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-200")}/>
        <button className="bg-rose-300 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-300")}/>
        <button className="bg-rose-400 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-400")}/>
        <button className="bg-rose-500 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-500")}/>
        <button className="bg-rose-600 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-600")}/>
        <button className="bg-rose-700 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-700")}/>
        <button className="bg-rose-800 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-800")}/>
        <button className="bg-rose-900 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-900")}/>
        <button className="bg-rose-950 w-7 h-7 rounded-full hover:outline focus:outline" onClick={()=>setColor("rose-950")}/>
        </>
	);
}
